#-------------------------------------
#  Lab06 - Work this GitHub Actions
#  @Kyala16
#-------------------------------------

name: bank

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build banking_lib
        shell: bash
        run: |
          cd banking && cd built
          cmake ..
          cmake --build .
          
  Test_banking:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        shell: bash
        run: |
          cd built
          ./testBanking

