#-------------------------------------
#  Lab06 - Work this GitHub Actions
#  @Kyala16
#-------------------------------------

name: bank

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build banking_lib
        shell: bash
        run: |
          cd banking
          mkdir built && cd built
          cmake ..
          cmake --build .
          
  Test_banking:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: prepare environment
        run:  |
              sudo apt install git && git submodule update --init
              sudo apt install lcov
      
      - name: Test
        run: |
          mkdir built && cd built
          CXX=g++-6 cmake -DCOVERAGE=1 ..
          

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${ 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 }
          path-to-lcov: ./lab06/built/banking.info
